"use client"
import React from "react"
import {useTranslations} from "next-intl"
import {CiLaptop} from "react-icons/ci"
import {BsPhone} from "react-icons/bs"
import {TbWorldSearch} from "react-icons/tb"
import SectionTitle from "@/src/components/common/section-title"
import OurWorkSlider from "@/src/components/all-sliders-component/service-single-page-sliders/ourwork-slider"
import ParallaxPart from "@/src/components/landing-parallax"
export default function OurworkSection(){const t=useTranslations("serviceDetail.work"),services=useTranslations("services"),icons=[<CiLaptop key="0"/>,<BsPhone key="1"/>,<TbWorldSearch key="2"/>,<CiLaptop key="3"/>,<BsPhone key="4"/>,<TbWorldSearch key="5"/>],images=["/pic1.png","/pic2.png","/pic3.png","/pic1.png","/pic2.png","/pic3.png"],items=icons.map((svg,i)=>({id:i+1,bgImg:images[i],number:String(i+1).padStart(2,"0"),svg,title:services(`items.${i}.title`),desc:services(`items.${i}.description`)}));return <section className="w-full pb-10"><div className="serviceCont"><div className="hidden lg:grid lg:grid-cols-12 gap-5"><OurWorkSlider service={items} title={t("title")} description={t("description")}/></div><div className="container lg:hidden"><SectionTitle classes="text-g21" title={t("title")}/><p className="text-g8 text-justify text-base leading-6 font-PoppinsLight pb-6">{t("description")}</p><ParallaxPart/></div></div></section>}