import './globals.css'
import './style/landing.css'
import './style/media.css'
import './style/sliders.css'
import './style/service-single-page.css'
import './style/about.css'
import './style/weblog.css'

// import { Inter } from 'next/font/google'
require("dotenv").config();
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gf'>
       <Navbar />
       {children}
       <Footer />
      </body>
    </html>
  )
}
