import "./globals.css";
import "./style/landing.css";
import "./style/media.css";
import "./style/sliders.css";
import "./style/service-single-page.css";
import "./style/about.css";
import "./style/weblog.css";
import "./style/video.css";

// import { Inter } from 'next/font/google'
require("dotenv").config();
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

// const inter = Inter({ subsets: ['latin'] })
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="Te99GpNYx_dMXAGjx_zT6mk9EK-OlmFAyiuV6FaGJKw"
        />
        <title>Gandom Software Group | Web Development Services</title>
        <meta name="description" content="Gandom provides top-tier SEO software solutions and bespoke web development services tailored to elevate your digital presence and drive business success." />
        <meta name="keywords" content="SEO, web development, Gandom, digital marketing, SEO tools, website services, online branding, programming, tech solutions" />
        <meta name="robots" content="index, follow" />
        {/* <link rel="canonical" href="https://gandom.link" /> */}

        <meta property="og:type" content="website" />
        <meta property="og:title" content="Gandom Pioneers in SEO Software and Web Development Services" />
        <meta property="og:description" content="Discover Gandom's premium SEO software and custom web development services to power up your online presence." />
        <meta property="og:url" content="https://gandom.link" />
        <meta property="og:site_name" content="Gandom" />
        <meta property="og:image" content="https://gandom.link/og-image.jpg" /> 

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Gandom Pioneers in SEO Software and Web Development Services" />
        <meta name="twitter:description" content="Boost your online performance with Gandom's industry-leading SEO software and customized web development offerings." />
        <meta name="twitter:image" content="https://gandom.link/twitter-image.jpg" /> 
        <meta name="twitter:site" content="@GandomOfficial" />

      </head>
      <body className="bg-gf">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
