const rows = [
["navigation.search","navigation","جست‌وجو","Search"],
["landing.our_specialty.title","landing","شریک فنی شما","Your technology partner"],
["landing.our_specialty.sub_title","landing","از ایده تا محصولی که رشد می‌کند","From idea to a product that scales"],
["landing.our_specialty.context","landing","گندم یک آژانس نرم‌افزاری است که به کسب‌وکارها برای طراحی، ساخت و توسعه محصولات دیجیتال کمک می‌کند. از کشف مسئله و طراحی تجربه کاربری تا توسعه وب، اپلیکیشن، زیرساخت و رشد محصول، کنار تیم شما می‌مانیم.","Gandom is a software agency that helps businesses design, build and grow digital products. From product discovery and UX design to web and mobile development, infrastructure and growth, we work as an extension of your team."],
["landing.our_services.title","landing","خدمات ما","Our services"],
["landing.our_services.context","landing","برای ساخت یک محصول دیجیتال موفق، طراحی، مهندسی و رشد باید در یک مسیر باشند. تیم چندتخصصی ما این مسیر را یکپارچه پیش می‌برد.","Successful digital products need design, engineering and growth moving in the same direction. Our multidisciplinary team brings that journey together."],
["landing.our_work.title","landing","محصولاتی که با مسئله واقعی شروع شدند","Products built around real problems"],
["landing.our_work.context","landing","ما فقط کد تحویل نمی‌دهیم. مسئله کسب‌وکار را می‌فهمیم، راه‌حل را اعتبارسنجی می‌کنیم و محصولی قابل نگهداری می‌سازیم که بتواند همراه کاربران و بازار رشد کند. همکاری ما بعد از انتشار نیز با پشتیبانی، تحلیل و بهبود مستمر ادامه دارد.","We do more than ship code. We understand the business problem, validate the solution and build maintainable products that evolve with users and the market. After launch, we stay involved through support, analytics and continuous improvement."],
["landing.about_us.title","landing","درباره گندم","About Gandom"],
["landing.about_us.context","landing","ما تیمی از طراحان محصول، توسعه‌دهندگان و متخصصان رشد هستیم که با نگاه محصول‌محور، ایده‌ها را به نرم‌افزارهای قابل اتکا تبدیل می‌کنیم. شفافیت، کیفیت فنی و نتیجه کسب‌وکار سه اصل همکاری ماست.","We are product designers, software engineers and growth specialists who turn ideas into dependable software. Transparency, technical quality and business outcomes guide every engagement."],
["landing.trust","landing","همراه مورد اعتماد کسب‌وکارهای رو به رشد","Trusted by growing businesses"],
["small_contact.title","landing","برای ساخت یا توسعه محصول دیجیتال‌تان آماده‌اید؟","Ready to build or improve your digital product?"],
["small_contact.click","landing","شروع گفتگو","Start a conversation"],
["small_contact.support","landing","تیم ما آماده شنیدن مسئله شماست","Our team is ready to understand your challenge"],
["services.title","services","خدمات آژانس نرم‌افزاری","Software agency services"],
["services.items.0.title","services","توسعه نرم‌افزار اختصاصی","Custom software development"],
["services.items.0.description","services","سامانه‌های اختصاصی، پنل‌های مدیریتی، CRM و ERP، پلتفرم‌های SaaS و راهکارهای یکپارچه را با معماری مقیاس‌پذیر و متناسب با فرآیند واقعی کسب‌وکار شما طراحی و توسعه می‌دهیم.","We design and build custom platforms, admin systems, CRM and ERP solutions, SaaS products and integrations with scalable architecture tailored to your business workflows."],
["services.items.1.title","services","سئو و رشد ارگانیک","SEO and organic growth"],
["services.items.1.description","services","با سئوی تکنیکال، استراتژی محتوا، تحقیق کلمات کلیدی و تحلیل داده کمک می‌کنیم محصول شما در جست‌وجو دیده شود و ترافیک هدفمند و پایدار بسازد.","Through technical SEO, content strategy, keyword research and analytics, we help your product earn visibility and sustainable, qualified traffic."],
["services.items.2.title","services","طراحی محصول و UI/UX","Product and UI/UX design"],
["services.items.2.description","services","با تحقیق کاربر، معماری اطلاعات، پروتوتایپ و طراحی سیستم، تجربه‌ای ساده و منسجم می‌سازیم که هم برای کاربر قابل فهم باشد و هم اهداف کسب‌وکار را جلو ببرد.","We combine user research, information architecture, prototyping and design systems to create clear experiences that serve users and business goals."],
["services.items.3.title","services","طراحی و توسعه وب","Web design and development"],
["services.items.3.description","services","وب‌سایت‌های شرکتی، فروشگاهی و پلتفرم‌های تحت وب را سریع، واکنش‌گرا، بهینه برای سئو و آماده توسعه آینده پیاده‌سازی می‌کنیم.","We create fast, responsive and SEO-ready corporate websites, ecommerce experiences and web platforms designed for future growth."],
["services.items.4.title","services","استراتژی و تولید محتوا","Content strategy and production"],
["services.items.4.description","services","برای برند و محصول شما لحن، تقویم و ساختار محتوایی می‌سازیم و محتوای تخصصی، شبکه‌های اجتماعی و کمپین‌های دیجیتال را هدفمند تولید می‌کنیم.","We define the voice, calendar and content system for your brand, then produce focused editorial, social and campaign content."],
["services.items.5.title","services","توسعه اپلیکیشن موبایل","Mobile app development"],
["services.items.5.description","services","اپلیکیشن‌های اندروید و iOS را از طراحی تجربه تا توسعه، انتشار و پشتیبانی با تمرکز بر عملکرد، امنیت و تجربه روان کاربر می‌سازیم.","We take Android and iOS apps from experience design through engineering, release and support, focusing on performance, security and usability."],
["portfolio.title","portfolio","نمونه همکاری‌ها","Selected work"],
["portfolio.items.0.title","portfolio","پلتفرم آموزش آنلاین","Online learning platform"],
["portfolio.items.0.subtitle","portfolio","تجربه یادگیری یکپارچه برای دانش‌آموزان","A connected learning experience for students"],
["portfolio.items.0.description","portfolio","طراحی و توسعه بستری برای دوره‌های آموزشی، آزمون، گزارش پیشرفت و تعامل مدرس و دانش‌آموز با معماری آماده رشد.","A scalable platform for courses, assessments, progress reporting and interaction between teachers and students."],
["portfolio.items.1.title","portfolio","تستاتو","Testato"],
["portfolio.items.1.subtitle","portfolio","اپلیکیشن آموزش و آزمون دانش‌آموزی","Learning and assessment for students"],
["portfolio.items.1.description","portfolio","محصولی موبایل‌محور برای تمرین، آزمون و تحلیل عملکرد که مسیر مطالعه را برای دانش‌آموز و مشاور شفاف‌تر می‌کند.","A mobile-first product for practice, testing and performance analysis that clarifies study progress for students and advisors."],
["portfolio.items.2.title","portfolio","سامانه مدیریت کسب‌وکار","Business operations platform"],
["portfolio.items.2.subtitle","portfolio","یکپارچه‌سازی فرآیندهای روزمره","Connecting everyday operations"],
["portfolio.items.2.description","portfolio","داشبوردی اختصاصی برای مدیریت مشتریان، سفارش‌ها، گزارش‌ها و گردش کار تیمی با دسترسی‌های امن و قابل تنظیم.","A custom dashboard for customers, orders, reporting and team workflows with secure, configurable access."],
["portfolio.items.3.title","portfolio","فروشگاه آنلاین مقیاس‌پذیر","Scalable ecommerce experience"],
["portfolio.items.3.subtitle","portfolio","از کشف محصول تا خرید روان","From product discovery to a smooth checkout"],
["portfolio.items.3.description","portfolio","تجربه فروش آنلاین سریع و قابل توسعه با مدیریت موجودی، پرداخت، کمپین و گزارش‌های تصمیم‌ساز.","A fast, extensible commerce experience with inventory, payment, campaign and decision-ready reporting capabilities."],
["portfolio.items.4.title","portfolio","وب‌سایت برند و هویت دیجیتال","Brand website and digital identity"],
["portfolio.items.4.subtitle","portfolio","روایتی روشن و متمایز از برند","A clear and distinctive brand story"],
["portfolio.items.4.description","portfolio","بازطراحی هویت و وب‌سایت برند با تمرکز بر پیام، تجربه کاربری، سرعت و تبدیل بازدیدکننده به سرنخ فروش.","A refreshed identity and website focused on messaging, user experience, speed and converting visitors into qualified leads."],
["about.header.title","about","یک تیم محصول برای ساخت نرم‌افزارهای اثرگذار","A product team for meaningful software"],
["about.header.description","about","ما کنار سازمان‌ها و استارتاپ‌ها کار می‌کنیم تا مسئله‌های پیچیده را به محصولات دیجیتال ساده، قابل اتکا و آماده رشد تبدیل کنیم.","We work with organizations and startups to turn complex challenges into clear, dependable digital products built to grow."],
["about.values.title","about","چیزهایی که کیفیت همکاری ما را می‌سازند","What makes our partnerships work"],
["about.values.0.title","about","نگاه محصول‌محور","Product thinking"],
["about.values.0.description","about","قبل از انتخاب فناوری، مسئله، کاربر و نتیجه مورد انتظار کسب‌وکار را روشن می‌کنیم.","Before choosing technology, we clarify the problem, the user and the business outcome."],
["about.values.1.title","about","کیفیت مهندسی","Engineering quality"],
["about.values.1.description","about","کدی خوانا، تست‌پذیر و قابل نگهداری می‌نویسیم تا محصول در آینده هزینه پنهان نسازد.","We write maintainable, testable code so today's product does not become tomorrow's hidden cost."],
["about.values.2.title","about","همکاری شفاف","Transparent collaboration"],
["about.values.2.description","about","وضعیت، تصمیم‌ها و ریسک‌ها را روشن به اشتراک می‌گذاریم و بخشی واقعی از تیم شما می‌شویم.","We communicate progress, decisions and risks clearly and operate as a genuine extension of your team."],
["about.values.3.title","about","بهبود مستمر","Continuous improvement"],
["about.values.3.description","about","بعد از انتشار با داده و بازخورد یاد می‌گیریم و محصول را مرحله‌به‌مرحله بهتر می‌کنیم.","After launch, we learn from data and feedback and improve the product in meaningful increments."],
["about.join.title","about","به تیم گندم بپیوندید","Join the Gandom team"],
["about.join.description","about","اگر از حل مسئله‌های واقعی، یادگیری مداوم و ساخت محصول با یک تیم مسئولیت‌پذیر لذت می‌برید، دوست داریم شما را بشناسیم.","If you enjoy solving real problems, learning continuously and building products with an accountable team, we would love to meet you."],
["about.join.action","about","ارسال رزومه","Send your resume"],
["about.contact.title","about","بیایید درباره چیزی که می‌توانیم با هم بسازیم صحبت کنیم","Let's talk about what we can build together"],
["about.contact.description","about","چه در ابتدای یک ایده باشید، چه محصولی فعال داشته باشید که به بازطراحی، توسعه یا مقیاس‌پذیری نیاز دارد، تیم ما می‌تواند مسیر مناسب را با شما طراحی و اجرا کند.","Whether you have an early idea or an existing product that needs redesign, development or scaling, our team can shape and deliver the right path with you."],
["contact.title","contact","تماس با ما","Contact us"],
["contact.subtitle","contact","مسئله و هدفتان را برای ما بنویسید؛ برای پیدا کردن مسیر مناسب با شما تماس می‌گیریم.","Tell us about your challenge and goal. We will get back to you to explore the right path."],
["share.button.see_more","shared","مشاهده بیشتر","See more"],
["shared.see_details","shared","مشاهده جزئیات","See details"],
["shared.send_message","shared","ارسال پیام","Send message"],
["share.footer.copyright","shared","© ۲۰۲۶ گندم؛ تمامی حقوق محفوظ است.","© 2026 Gandom. All rights reserved."],
["navigation.current","navigation","صفحه","Page"],
["navigation.items.0.title","navigation","خدمات ما","Our services"],
["navigation.items.1.title","navigation","خانه","Home"],
["navigation.items.2.title","navigation","تماس با ما","Contact us"],
["navigation.items.3.title","navigation","مشتریان","Clients"],
["navigation.items.4.title","navigation","وبلاگ","Weblog"],
["navigation.items.5.title","navigation","نمونه‌کارها","Portfolio"],
["navigation.items.6.title","navigation","درباره ما","About us"],
["serviceDetail.specialize.title","serviceDetail","راهکارهایی که توسعه می‌دهیم","Solutions we build"],
["serviceDetail.specialize.0.title","serviceDetail","CRM و ERP","CRM and ERP"],
["serviceDetail.specialize.0.description","serviceDetail","سامانه‌های یکپارچه برای مدیریت مشتری، فروش، منابع و عملیات روزمره.","Connected systems for customer, sales, resource and operations management."],
["serviceDetail.specialize.1.title","serviceDetail","تجارت الکترونیک","Ecommerce"],
["serviceDetail.specialize.1.description","serviceDetail","فروشگاه‌ها و تجربه‌های خرید سریع با مدیریت سفارش، پرداخت و موجودی.","Fast commerce experiences with order, payment and inventory management."],
["serviceDetail.specialize.2.title","serviceDetail","مارکت‌پلیس","Marketplaces"],
["serviceDetail.specialize.2.description","serviceDetail","پلتفرم‌های چندفروشنده با گردش کار، تسویه و دسترسی‌های قابل تنظیم.","Multi-vendor platforms with configurable workflows, settlements and access."],
["serviceDetail.specialize.3.title","serviceDetail","محصولات SaaS","SaaS products"],
["serviceDetail.specialize.3.description","serviceDetail","محصولات اشتراکی امن و مقیاس‌پذیر برای بازارهای تخصصی.","Secure, scalable subscription products for focused markets."],
["serviceDetail.specialize.4.title","serviceDetail","اپلیکیشن‌های درخواستی","On-demand applications"],
["serviceDetail.specialize.4.description","serviceDetail","تجربه‌های موبایل و وب برای اتصال سریع کاربر، سرویس‌دهنده و عملیات.","Mobile and web experiences connecting customers, providers and operations."],
["serviceDetail.specialize.5.title","serviceDetail","یکپارچه‌سازی و اتوماسیون","Integration and automation"],
["serviceDetail.specialize.5.description","serviceDetail","اتصال ابزارهای موجود و خودکارسازی کارهای تکراری برای کاهش خطا و هزینه.","Connecting existing tools and automating repetitive work to reduce errors and cost."],
["serviceDetail.work.title","serviceDetail","نمونه همکاری‌ها","Selected work"],
["serviceDetail.work.description","serviceDetail","چند نمونه از محصولاتی که با همکاری تیم‌های کسب‌وکار طراحی و توسعه داده‌ایم.","A selection of products designed and delivered alongside our clients' teams."],
["serviceDetail.reasons.title","serviceDetail","چرا با گندم همکاری کنید؟","Why work with Gandom?"],
["serviceDetail.reasons.0.title","serviceDetail","تمرکز بر نتیجه","Outcome focused"],
["serviceDetail.reasons.0.description","serviceDetail","تصمیم‌های محصول و فناوری را به نتیجه قابل سنجش کسب‌وکار متصل می‌کنیم.","We connect product and technology decisions to measurable business outcomes."],
["serviceDetail.reasons.1.title","serviceDetail","تیم چندتخصصی","Multidisciplinary team"],
["serviceDetail.reasons.1.description","serviceDetail","طراحی، توسعه، زیرساخت و رشد در یک تیم هماهنگ کنار هم کار می‌کنند.","Design, engineering, infrastructure and growth work as one aligned team."],
["serviceDetail.reasons.2.title","serviceDetail","همکاری شفاف","Transparent delivery"],
["serviceDetail.reasons.2.description","serviceDetail","پیشرفت، تصمیم‌ها و ریسک‌ها را منظم و روشن با شما به اشتراک می‌گذاریم.","We communicate progress, decisions and risks clearly and consistently."],
["serviceDetail.reasons.3.title","serviceDetail","کیفیت فنی","Technical quality"],
["serviceDetail.reasons.3.description","serviceDetail","کد قابل نگهداری، تست و مانیتورینگ را بخشی از تعریف تحویل می‌دانیم.","Maintainable code, testing and monitoring are part of our definition of done."],
["serviceDetail.reasons.4.title","serviceDetail","آماده رشد","Built to scale"],
["serviceDetail.reasons.4.description","serviceDetail","راه‌حل را متناسب با امروز می‌سازیم، بدون اینکه مسیر رشد فردا را ببندیم.","We solve today's need without closing the path to tomorrow's growth."],
["serviceDetail.reasons.5.title","serviceDetail","پشتیبانی واقعی","Reliable support"],
["serviceDetail.reasons.5.description","serviceDetail","پس از انتشار برای رفع مسئله، تحلیل داده و توسعه نسخه‌های بعدی کنار شما می‌مانیم.","After launch, we stay for issue resolution, analytics and future iterations."],
["serviceDetail.process.title","serviceDetail","فرایند همکاری","Our process"],
["serviceDetail.process.0.title","serviceDetail","کشف","Discovery"],
["serviceDetail.process.0.description","serviceDetail","مسئله، کاربر، محدودیت‌ها و معیار موفقیت را با هم روشن می‌کنیم.","We clarify the problem, users, constraints and success metrics together."],
["serviceDetail.process.1.title","serviceDetail","طراحی","Design"],
["serviceDetail.process.1.description","serviceDetail","جریان‌ها و پروتوتایپ را پیش از توسعه اعتبارسنجی می‌کنیم.","We validate journeys and prototypes before expensive implementation."],
["serviceDetail.process.2.title","serviceDetail","برنامه فنی","Technical plan"],
["serviceDetail.process.2.description","serviceDetail","معماری، دامنه نسخه و برنامه تحویل مرحله‌ای را مشخص می‌کنیم.","We define architecture, release scope and an incremental delivery plan."],
["serviceDetail.process.3.title","serviceDetail","توسعه","Development"],
["serviceDetail.process.3.description","serviceDetail","محصول را در چرخه‌های کوتاه می‌سازیم و پیشرفت را قابل مشاهده نگه می‌داریم.","We build in short cycles and keep progress visible throughout delivery."],
["serviceDetail.process.4.title","serviceDetail","تست و انتشار","QA and launch"],
["serviceDetail.process.4.description","serviceDetail","کیفیت، امنیت و عملکرد را بررسی و انتشار را کنترل‌شده انجام می‌دهیم.","We verify quality, security and performance and release in a controlled way."],
["serviceDetail.process.5.title","serviceDetail","رشد","Growth"],
["serviceDetail.process.5.description","serviceDetail","با داده و بازخورد، نسخه‌های بعدی را اولویت‌بندی و اجرا می‌کنیم.","We use data and feedback to prioritize and deliver the next iterations."],
["serviceDetail.support.title","serviceDetail","پشتیبانی پس از انتشار","Support after launch"],
["serviceDetail.support.description","serviceDetail","پایداری محصول برای ما بخشی از تحویل است. مانیتورینگ، رفع خطا، به‌روزرسانی امنیتی، بهبود عملکرد و توسعه قابلیت‌های بعدی را با سطح خدمات روشن ادامه می‌دهیم تا تیم شما برای رشد محصول یک شریک فنی پاسخ‌گو داشته باشد.","Product reliability is part of delivery. We continue with monitoring, issue resolution, security updates, performance improvements and new capabilities under a clear support model, giving your team a responsive technical partner for growth."],
["serviceDetail.message.title","serviceDetail","برای توسعه محصولتان به یک تیم فنی نیاز دارید؟","Need a technical team to grow your product?"],
["serviceDetail.message.mobileTitle","serviceDetail","درباره پروژه صحبت کنیم","Let's discuss your project"],
["serviceDetail.header.subtitle","serviceDetail","خدمات تخصصی","Specialist services"],
["serviceDetail.header.join","serviceDetail","همکاری با ما","Work with us"],
["serviceDetail.header.portfolio","serviceDetail","نمونه‌کارها","Portfolio"],
["forms.getInTouch","forms","با ما در ارتباط باشید","Get in touch"],
["forms.name","forms","نام","Name"],
["forms.phone","forms","شماره تماس","Phone"],
["forms.email","forms","ایمیل","Email"],
["forms.message","forms","پیام","Message"],
["forms.cv","forms","لینک رزومه","Resume link"],
["forms.sending","forms","در حال ارسال...","Sending..."],
["forms.success","forms","پیام شما با موفقیت ثبت شد.","Your message was sent successfully."],
["forms.error","forms","ارسال پیام انجام نشد.","The message could not be sent."],
["contact.phone","contact","۰۹۱۱۴۱۱۲۲۵","0911411225"],
["contact.email","contact","info@gandom.link","info@gandom.link"],
["contact.location","contact","دفتر گندم","Gandom office"],
["forms.successTitle","forms","ارسال موفق","Sent successfully"],
["forms.errorTitle","forms","ارسال ناموفق","Something went wrong"],
["forms.validationTitle","forms","اطلاعات فرم کامل نیست","Please check the form"],
["forms.required","forms","لطفاً همه فیلدهای ضروری را کامل کنید.","Please complete all required fields."],
["forms.invalidEmail","forms","فرمت ایمیل معتبر نیست.","Please enter a valid email address."],
["forms.invalidPhone","forms","شماره تماس معتبر نیست.","Please enter a valid phone number."],
["forms.contentShort","forms","متن پیام باید حداقل ۱۰ کاراکتر باشد.","The message must be at least 10 characters long."]
]
export const siteContentDefinitions = rows.map(([key, group, fa, en], sortOrder) => ({key, group, label: key, valueType:"text", translations:{fa,en}, sortOrder, isActive:true}))
export function createDefaultSiteMessages(locale){const result={};for(const item of siteContentDefinitions)setNestedValue(result,item.key,item.translations[locale]||item.translations.en);return result}
export function setNestedValue(target,path,value){const parts=path.split(".");let cursor=target;parts.forEach((part,index)=>{if(index===parts.length-1)cursor[part]=value;else cursor=cursor[part]||={}});return target}
export function mergeDeep(target,source){for(const [key,value] of Object.entries(source||{})){if(value&&typeof value==="object"&&!Array.isArray(value))target[key]=mergeDeep(target[key]&&typeof target[key]==="object"?target[key]:{},value);else target[key]=value}return target}
