import { writeFile } from "node:fs/promises"
import path from "node:path"
import { sqlite } from "../src/db/index.mjs"

const tables = {
  teamMembers: "TeamMember",
  articles: "Article",
  siteContents: "SiteContent",
  articleComments: "ArticleComment",
}
const snapshot = Object.fromEntries(Object.entries(tables).map(([key, table]) => {
  const rows = sqlite.prepare(`SELECT * FROM \`${table}\` ORDER BY id`).all()
  return [key, table === "ArticleComment" ? rows.map((row) => ({ ...row, email: null })) : rows]
}))
const target = path.join(process.cwd(), "scripts", "seed-current-data.mjs")
const source = `// Generated by npm run db:seed:export. Review before committing.\nimport { sqlite } from "../src/db/index.mjs"\n\nconst snapshot = ${JSON.stringify(snapshot, null, 2)}\n\nfunction insertRows(table, rows, conflictColumn, omittedColumns = []) {\n  if (!rows.length) return\n  const columns = Object.keys(rows[0]).filter((column) => !omittedColumns.includes(column))\n  const quotedColumns = columns.map((column) => \`\\\`\${column}\\\`\`).join(", ")\n  const placeholders = columns.map((column) => \`@\${column}\`).join(", ")\n  const statement = sqlite.prepare(\`INSERT INTO \\\`\${table}\\\` (\${quotedColumns}) VALUES (\${placeholders}) ON CONFLICT(\\\`\${conflictColumn}\\\`) DO NOTHING\`)\n  for (const row of rows) statement.run(Object.fromEntries(columns.map((column) => [column, row[column]])))\n}\n\ntry {\n  sqlite.pragma("foreign_keys = ON")\n  sqlite.transaction(() => {\n    insertRows("TeamMember", snapshot.teamMembers, "id")\n    insertRows("Article", snapshot.articles, "id")\n    insertRows("SiteContent", snapshot.siteContents, "key", ["id"])\n    insertRows("ArticleComment", snapshot.articleComments, "id")\n  })()\n  console.log(\`Content seeded: \${snapshot.teamMembers.length} team members, \${snapshot.articles.length} articles, \${snapshot.siteContents.length} site contents, \${snapshot.articleComments.length} comments.\`)\n} finally { sqlite.close() }\n`
await writeFile(target, source, "utf8")
console.log(`Seed exported to ${target}. Admins, sessions and form submissions were intentionally excluded; comment emails were redacted.`)
sqlite.close()
