import "dotenv/config"
import { writeFile } from "node:fs/promises"
import path from "node:path"
import { closeDatabasePool, pool } from "../src/db/index.mjs"

const tables = {
  teamMembers: "TeamMember",
  articles: "Article",
  siteContents: "SiteContent",
  articleComments: "ArticleComment",
}

try {
  const snapshot = {}
  for (const [key, table] of Object.entries(tables)) {
    const [rows] = await pool.query("SELECT * FROM ?? ORDER BY id", [table])
    snapshot[key] = table === "ArticleComment"
      ? rows.map((row) => ({ ...row, email: null }))
      : rows
  }

  const target = path.join(process.cwd(), "scripts", "seed-current-data.mjs")
  const source = `// Generated by npm run db:seed:export. Review before committing.
import "dotenv/config"
import { closeDatabasePool } from "../src/db/index.mjs"
import { seedSnapshot } from "./seed-runtime.mjs"

const snapshot = ${JSON.stringify(snapshot, null, 2)}

try {
  await seedSnapshot(snapshot)
} finally {
  await closeDatabasePool()
}
`
  await writeFile(target, source, "utf8")
  console.log(`Seed exported from MariaDB to ${target}. Private tables were excluded and comment emails were redacted.`)
} finally {
  await closeDatabasePool()
}
